### ISSUE TITLE
Copyright concern of this dataset

### ISSUE THREAD

**Issue by zhanh-he** [BetsyTang/ATEPP#3]
Hi, can I get some detail of the copyright in this dataset? According to the papar, it said  "we download each track from a corresponding open source audio at YouTube Music".

But I check the csv file that most Youtube music downloaded is provided by the Universal Music Group, and the performed pianists are generally not "died over 70 year" so I assuming their arrangements are under the copyright. 

Would you detail the "open source audio" about how this open souce? And same concern for the sheet music. For the pieces in MuseScore, does there scores are non-provided licenses (so have copyright issue), or did provide the opensource licenses? MuseScore is open to public and non-careful management the copyright, so made things become sensitive.

This is a very promising dataset, but unfortunately I need to address the Univerisity's concerns regarding copyright before the further research.

Best regards <3

**Comment by tangjjbetsy** [comment]
Hi,

Thank you for your inquiry and for highlighting these concerns. Here are detailed responses regarding the copyright aspects of the dataset:

1. **Audio Downloading and Collection:** 
   We followed the procedures outlined in [Giant-Piano](https://github.com/bytedance/GiantMIDI-Piano) for downloading and collecting audio tracks. Please read our disclaimer carefully before using the dataset. The concept of "fair use" in copyright law allows for limited use of copyrighted material without requiring permission from the rights holders for purposes such as criticism, comment, news reporting, teaching, scholarship, and research. Since all the audio tracks were used strictly for research purposes, we believe this aligns with the "fair use" policy.

2. **Sheet Music:**
   As you mentioned, MuseScore does not always clearly address or carefully manage copyright issues. Similar to the audio tracks, we consider the use of these scores to fall under the "fair use" policy due to their application in research. The "fair use" policy is applicable in contexts where the use is transformative, does not affect the market value of the original work, and is limited in scope, particularly for educational and scholarly purposes.

3. **Distribution of Audio and Transcriptions:**
   To address copyright concerns, we have not released the audio files, only the transcriptions. For non-commercial use of the audio tracks, you may contact us to sign an agreement, after which we can provide you with a copy.
